### ISSUE TITLE
"comment": "Unable to manage file: 'hash_type'",

### ISSUE THREAD

**Issue by WraithCadmus** [jenkinsci/saltstack-plugin#50]
Hello, we're using this plugin for deploying freshly built jar files to our dev servers and we're getting the error in the title in the Salt output.

```
"file_|-java-jar-file_|-/opt/project/api.jar_|-managed":     {
  "comment": "Unable to manage file: 'hash_type'",
  "pchanges": {},
  "name": "/opt/project/api.jar",
  "start_time": "10:48:47.280779",
  "result": false,
  "duration": 2972.47,
  "__run_num__": 9,
  "changes": {},
  "__id__": "java-jar-file"
 },
```

I wonder if this has anything to do with the fact that Salt statement has "skip_verify: True" in it and the plugin isn't parsing what it's sending to Salt properly as a result? See attached a redacted version of the config (is this the right way to pass a pillar?).
![saltfail](https://cloud.githubusercontent.com/assets/18036904/20923737/cbec837a-bba5-11e6-9a8c-ac5e9ce8d175.PNG)

And finally here is the Salt statement that java-app is running to push that file

```
java-jar-file:
  file.managed:
    - name: /opt/{{ pillar['java-app']['app-name'] }}/{{ pillar['java-app']['jar-name'] }}.jar
    - source: {{ pillar ['java-app']['autodeploy-url'] }}
    - skip_verify: True
    - user: java-app
    - group: java-app
    - listen_in:
      - service: {{ pillar['java-app']['app-name'] }}
    - require:
      - file: java-app-home
      - file: java-app-service
      - user: java-app
      - group: java-app
```

I'm fairly sure the issue is in the plugin, as I am able to successfully run the same statement by hand using curl so I think the API is configured properly.

Sadly Jenkins isn't my forte so please let me know if there's more information you need or more diagnostics I can get from Jenkins and/or the plugin.

Thanks

**Comment by mchugh19** [comment]
Can you enable the debugging option for the jenkins plugin? This should give you a log of what exactly the plugin is submitting to the salt-api. https://wiki.jenkins-ci.org/display/JENKINS/saltstack-plugin#Logging%20Configuration

Also, in glancing at the screenshot, you might need to quote the entirety of the pillar like: "pillar={artifact: 'somevalue3', repo: 'othervalue:4'}"

**Comment by WraithCadmus** [comment]
Hello, I've upped the logging as requested, but even with Jenkins set to FINEST the http log doesn't contain the entire API call (though it does contain some other things from the FINEST level so I think I've done it correctly).

`Dec 14, 2016 3:20:25 PM FINEST sun.net.www.protocol.http.HttpURLConnection
KeepAlive stream used: https://salt.company.co.uk:8000
`

From the Salt logger I have the JSON string it's sending (redacted)

`Sending JSON: [{"client":"local","tgt":"devsvcapil0[1-3].company.co.uk","expr_form":"glob","fun":"state.sls","arg":["java-app","pillar={java-app: {autodeploy-url: 'https://jenkins.company.co.uk/job/Company%20Website%20API/223/uk.company.services$services-api/artifact/uk.company.services/services-api/0.0.1-SNAPSHOT/services-api-0.0.1-SNAPSHOT.jar'}}"]}]`

I am now quoting the pillar as you requested. There's also the received response, which matches what I was seeing in the console output, I think the relevant part is:

`"file_|-java-jar-file_|-/opt/api/services-api.jar_|-managed":{"comment":"Unable to manage file: 'hash_type'","pchanges":{},"name":"/opt/api/services-api.jar","start_time":"15:19:59.522704","result":false,"duration":2023.789,"__run_num__":9,"changes":{},"__id__":"java-jar-file"}`

I'm going to focus on getting the HTTP log, which I might be able to get from the API itself, or maybe find some clue there.

**Comment by mchugh19** [comment]
I was able to get salt to show the expected pillar information with running the `test.arg` function and arguments
```
tests.pillar-show, "pillar={java-app: {autodeploy-url: 'https://jenkins.company.co.uk/job/Company%20Website%20API/223/uk.company.services$services-api/artifact/uk.company.services/services-api/0.0.1-SNAPSHOT/services-api-0.0.1-SNAPSHOT.jar'}}"
```

I could then get the `state.sls` function to render the tests.pillar-show state of:
```
{% set url = salt['pillar.get']('java-app:autodeploy-url') %}

print_output:
  cmd.run:
    - name: echo "printing url {{ url }}"
```

Can you try that to see if your file.manage state operates properly?
